### ISSUE TITLE
Update APIs.

### ISSUE THREAD

**Issue by FarazPatankar** [tom-grey/fpl-api-graphql#4]
Hey,

I was just wondering if you were considering updating the library. I think most of the URLs are the same but they've switched out the `drf` for `api`.

Thanks!

**Comment by tgreyuk** [comment]
Thanks @FarazPatankar - i've had .a look and it looks like the urls have changed too so will need to investigate further.

**Comment by FarazPatankar** [comment]
Yeah, it seems like they've removed some of the URLs and you'd have to get them from the `bootstrap-static` URL itself. The `/teams` route is one of those cases.

**Comment by tgreyuk** [comment]
Apis now updated.
