### ISSUE TITLE
your package is not being installed

### ISSUE THREAD

**Issue by arpitsatyal** [tom-grey/fpl-api-graphql#5]
this is the error:

$ npm install fpl-api-graphql
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "fpl-api-graphql" under a package
npm ERR! also called "fpl-api-graphql". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ANIL RANA\AppData\Roaming\npm-cache\_logs\2019-09-03T11_32_31_369Z-debug.log

what shall i do?

**Comment by tgreyuk** [comment]
This suggests that the name in your package.json in the dir you are installing from is `fpl-api-graphql` ?

**Comment by arpitsatyal** [comment]
ok its installed. now what? how do i use it? i want to include this in my angular project

**Comment by tgreyuk** [comment]
You can set up your server using the example in the readme. Then you will need a bridge between Angular and the server. Have a look at https://www.apollographql.com/docs/angular/basics/setup/
